name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18, 20, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install deps
        run: yarn install

      - name: Run Codegen for GraphQL
        run: yarn run compile

      - name: Test
        run: yarn test
